### ISSUE TITLE
HTML

### ISSUE THREAD

**Issue by iseanc** [iseanc/prework-study-guide#1]
#HTML

## User Story
As a bootcamp student
I want the prework notes to be structured on a webpage
so that I can easily find and read information

##Acceptance Criteria
GIVEN a Prework Study Guide website
WHEN I visit the website in my browser
THEN I see four boxes titled HTML, CSS, Git, and JavaScript with associated notes listed

**Comment by Saurabhbangar0** [comment]
hiii My name is saurabh Bangar

code is 
<form action="/action_page.php" id="form1">
  <label for="fname">First name:</label>
  <input type="text" id="fname" name="fname"><br><br>
  <input type="submit" value="Submit">
</form>

<label for="lname">Last name:</label>
<input type="text" id="lname" name="lname" form="form1">

**Comment by iseanc** [comment]
Added HTML code for different notes sections, and some notes.
